name = "my-app2"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
kv_namespaces = [
  { binding = “ONEDRIVE_CF_INDEX_KV”, id = “onedrive_cf_index” }
]
